import { Injectable, NotFoundException } from '@nestjs/common';
import { BadRequestException } from '@nestjs/common';
import { Repository } from 'typeorm';
import { InjectRepository } from '@nestjs/typeorm';
import { UserInfo } from 'src/database/entities/user.entity';
import { TransferDto } from '../dtos/makeTransfer.dto';
import { InjectQueue } from '@nestjs/bullmq';
import { Queue } from 'bullmq';
import { transactionProcessing } from './transferProcessing';

@Injectable()
export class transferService {

  constructor(
    @InjectRepository(UserInfo)
    private userTable: Repository<UserInfo>,
    @InjectQueue("transactionQueue") private txQueue: Queue,


  ){}
  
  async transferFunds(transferDetails:TransferDto){
    const Tx = await this.txQueue.add('makeTransfer', transferDetails)
    console.log("🚀 TransactionId generated by queue ~ Tx:", Tx.id)

  
  }
   

  async getTransferHistory(transferDetails): Promise<any> {
  
  }

}
